esphome:
  name: esp32-s3-audio-board-voice
  friendly_name: ESP32-S3-Audio-Board Voice

esp32:
  board: esp32-s3-devkitc-1
  cpu_frequency: 240MHz
  flash_size: 16MB
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE: "16MB"
      CONFIG_ESPTOOLPY_FLASHMODE: "qio"
      CONFIG_ESPTOOLPY_FLASHFREQ: "80m"

      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y"

      CONFIG_SPIRAM_RODATA: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: "y"

      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"

      CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL: "98304"
      CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL: "8192"

      CONFIG_ESP_WIFI_RX_IRAM_OPT: "n"

      CONFIG_FREERTOS_PLACE_FUNCTIONS_INTO_FLASH: "y"

      CONFIG_BT_ENABLED: "n"

      CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY: "y"

psram:
  mode: octal
  speed: 80MHz
  ignore_not_found: false

logger:
  level: DEBUG
  logs:
    ring_buffer: WARN
    resampler_speaker: WARN
    speaker_mixer: INFO
    ld2410: INFO
    sensor: INFO

api:

ota:
  - platform: esphome
    id: ota_esphome

captive_portal:

i2c:
  id: i2c_bus
  scl: GPIO10
  sda: GPIO11
  scan: true
  frequency: 100kHz

tca9555:
  - id: tca9555_hub
    i2c_id: i2c_bus
    address: 0x20

i2s_audio:
  - id: i2s_output
    i2s_lrclk_pin:
      number: GPIO14
      allow_other_uses: true
    i2s_bclk_pin:
      number: GPIO13
      allow_other_uses: true
    i2s_mclk_pin:
      number: GPIO12
      allow_other_uses: true

  - id: i2s_input
    i2s_lrclk_pin:
      number: GPIO14
      allow_other_uses: true
    i2s_bclk_pin:
      number: GPIO13
      allow_other_uses: true
    i2s_mclk_pin:
      number: GPIO12
      allow_other_uses: true

audio_adc:
  - platform: es7210
    id: es7210_adc
    i2c_id: i2c_bus
    bits_per_sample: 16bit
    sample_rate: 16000

audio_dac:
  - platform: es8311
    id: es8311_dac
    i2c_id: i2c_bus
    bits_per_sample: 16bit
    sample_rate: 48000
    use_mclk: true

microphone:
  - platform: i2s_audio
    id: echo_microphone
    i2s_audio_id: i2s_input
    i2s_din_pin: GPIO15
    bits_per_sample: 16bit
    sample_rate: 16000
    adc_type: external
    adc: es7210_adc 
    i2s_mode: secondary
    use_apll: true
    mclk_multiple: 256

speaker:
  - platform: i2s_audio
    id: i2s_audio_speaker
    i2s_audio_id: i2s_output
    i2s_dout_pin: GPIO16
    dac_type: external
    audio_dac: es8311_dac
    sample_rate: 48000
    bits_per_sample: 16bit
    channel: stereo
    timeout: never
    buffer_duration: 100ms
    i2s_mode: secondary
    use_apll: true
    mclk_multiple: 256

  - platform: mixer
    id: speaker_mixer
    output_speaker: i2s_audio_speaker
    num_channels: 2
    source_speakers:
      - id: announcement_mixer_input
        timeout: never
      - id: media_mixer_input
        timeout: never

  - platform: resampler
    id: announcement_resampler
    output_speaker: announcement_mixer_input
    sample_rate: 48000
    bits_per_sample: 16
    buffer_duration: 500ms

  - platform: resampler
    id: media_resampler
    output_speaker: media_mixer_input
    sample_rate: 48000
    bits_per_sample: 16
    buffer_duration: 500ms

light:
  - platform: esp32_rmt_led_strip
    id: led
    name: None
    disabled_by_default: true
    entity_category: config
    pin: GPIO38
    default_transition_length: 0s
    chipset: WS2812
    num_leds: 7
    rgb_order: grb
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 250ms
          update_interval: 250ms
          min_brightness: 50%
          max_brightness: 100%
      - pulse:
          name: "Fast Pulse"
          transition_length: 100ms
          update_interval: 100ms
          min_brightness: 50%
          max_brightness: 100%

media_player:
  - platform: speaker
    id: echo_media_player
    name: None
    buffer_size: 6000
    volume_min: 0.4
    volume_max: 0.85
    announcement_pipeline:
      speaker: announcement_resampler
      format: WAV
      num_channels: 2
    media_pipeline:
      speaker: media_resampler
      format: WAV
      num_channels: 2
    files:
      - id: timer_finished_wave_file
        file: https://github.com/esphome/wake-word-voice-assistants/raw/main/sounds/timer_finished.wav

    on_announcement:
      - if:
          condition:
            - microphone.is_capturing:
          then:
            - script.execute: stop_wake_word
      - light.turn_on:
          id: led
          blue: 100%
          red: 0%
          green: 0%
          brightness: 100%
          effect: none

    on_idle:
      - script.execute: start_wake_word
      - script.execute: reset_led

voice_assistant:
  id: va
  micro_wake_word:
  microphone:
    microphone: echo_microphone
    channels: 0
    gain_factor: 4
  media_player: echo_media_player
  noise_suppression_level: 2
  auto_gain: 31dBFS

  on_listening:
    - light.turn_on:
        id: led
        blue: 100%
        red: 0%
        green: 0%
        effect: "Slow Pulse"

  on_stt_vad_end:
    - light.turn_on:
        id: led
        blue: 100%
        red: 0%
        green: 0%
        effect: "Fast Pulse"

  on_tts_start:
    - light.turn_on:
        id: led
        blue: 100%
        red: 0%
        green: 0%
        brightness: 100%
        effect: none

  on_end:
    - wait_until:
        condition:
          - media_player.is_announcing:
        timeout: 0.5s
    - wait_until:
        condition:
          not:
            media_player.is_announcing:
        timeout: 30s
    - if:
        condition:
          - lambda: return id(wake_word_engine_location).current_option() == "On device";
        then:
          - wait_until:
              - and:
                  - not:
                      voice_assistant.is_running:
          - lambda: id(va).set_use_wake_word(false);
          - micro_wake_word.start:
    - script.execute: reset_led

  on_error:
    - light.turn_on:
        id: led
        red: 100%
        green: 0%
        blue: 0%
        brightness: 100%
        effect: none
    - delay: 2s
    - script.execute: reset_led

  on_client_connected:
    - delay: 2s
    - script.execute: start_wake_word

  on_client_disconnected:
    - script.execute: stop_wake_word

  on_timer_finished:
    - script.execute: stop_wake_word
    - wait_until:
        not:
          microphone.is_capturing:
    - switch.turn_on: timer_ringing
    - light.turn_on:
        id: led
        red: 0%
        green: 100%
        blue: 0%
        brightness: 100%
        effect: "Fast Pulse"
    - wait_until:
        - switch.is_off: timer_ringing
    - light.turn_off: led
    - switch.turn_off: timer_ringing

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: Button
    disabled_by_default: true
    entity_category: diagnostic
    id: echo_button
    on_multi_click:
      - timing:
          - ON for at least 50ms
          - OFF for at least 50ms
        then:
          - if:
              condition:
                switch.is_on: timer_ringing
              then:
                - switch.turn_off: timer_ringing
              else:
                - script.execute: start_wake_word

script:
  - id: reset_led
    then:
      - if:
          condition:
            - lambda: return id(wake_word_engine_location).current_option() == "On device";
            - switch.is_on: use_listen_light
          then:
            - light.turn_on:
                id: led
                red: 100%
                green: 89%
                blue: 71%
                brightness: 60%
          else:
            - if:
                condition:
                  - lambda: return id(wake_word_engine_location).current_option() != "On device";
                  - switch.is_on: use_listen_light
                then:
                  - light.turn_on:
                      id: led
                      red: 0%
                      green: 100%
                      blue: 100%
                      brightness: 60%
                else:
                  - light.turn_off: led

  - id: start_wake_word
    then:
      - if:
          condition:
            and:
              - not:
                  - voice_assistant.is_running:
              - lambda: return id(wake_word_engine_location).current_option() == "On device";
          then:
            - lambda: id(va).set_use_wake_word(false);
            - micro_wake_word.start:
      - if:
          condition:
            and:
              - not:
                  - voice_assistant.is_running:
              - lambda: return id(wake_word_engine_location).current_option() == "In Home Assistant";
          then:
            - lambda: id(va).set_use_wake_word(true);
            - voice_assistant.start_continuous:

  - id: stop_wake_word
    then:
      - if:
          condition:
            lambda: return id(wake_word_engine_location).current_option() == "In Home Assistant";
          then:
            - lambda: id(va).set_use_wake_word(false);
            - voice_assistant.stop:
      - if:
          condition:
            lambda: return id(wake_word_engine_location).current_option() == "On device";
          then:
            - micro_wake_word.stop

switch:
  - platform: gpio
    id: pa_enable
    name: "Audio Power Amplifier"
    restore_mode: ALWAYS_ON
    pin:
      tca9555: tca9555_hub
      number: 8

  - platform: template
    name: Use listen light
    id: use_listen_light
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config
    on_turn_on:
      - script.execute: reset_led
    on_turn_off:
      - script.execute: reset_led

  - platform: template
    id: timer_ringing
    optimistic: true
    restore_mode: ALWAYS_OFF
    on_turn_off:
      - lambda: |-
          id(echo_media_player)
            ->make_call()
            .set_command(media_player::MediaPlayerCommand::MEDIA_PLAYER_COMMAND_REPEAT_OFF)
            .set_announcement(true)
            .perform();
          id(echo_media_player)->set_playlist_delay_ms(speaker::AudioPipelineType::ANNOUNCEMENT, 0);
      - media_player.stop:
          announcement: true
    on_turn_on:
      - lambda: |-
          id(echo_media_player)
            ->make_call()
            .set_command(media_player::MediaPlayerCommand::MEDIA_PLAYER_COMMAND_REPEAT_ONE)
            .set_announcement(true)
            .perform();
          id(echo_media_player)->set_playlist_delay_ms(speaker::AudioPipelineType::ANNOUNCEMENT, 1000);
      - media_player.speaker.play_on_device_media_file:
          media_file: timer_finished_wave_file
          announcement: true
      - delay: 15min
      - switch.turn_off: timer_ringing

select:
  - platform: template
    entity_category: config
    name: Wake word engine location
    id: wake_word_engine_location
    optimistic: true
    restore_value: true
    options:
      - In Home Assistant
      - On device
    initial_option: On device
    on_value:
      - if:
          condition:
            lambda: return x == "In Home Assistant";
          then:
            - micro_wake_word.stop
            - delay: 500ms
            - lambda: id(va).set_use_wake_word(true);
            - voice_assistant.start_continuous
      - if:
          condition:
            lambda: return x == "On device";
          then:
            - lambda: id(va).set_use_wake_word(false);
            - voice_assistant.stop
            - delay: 500ms
            - micro_wake_word.start

micro_wake_word:
  on_wake_word_detected:
    - voice_assistant.start:
        wake_word: !lambda return wake_word;

  vad:

  models:
    - model: okay_nabu
    - model: hey_mycroft
    - model: hey_jarvis
