substitutions:
  name: esp32-s3-audio-board-voice
  friendly_name: ESP32-S3-Audio-Board Voice
packages:
  ESP32-S3-Audio-Board Voice: github://ichbaum/esphome-esp32_s3_audio_board/esp32-s3-audio-board-voice.yaml                                
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  
api:
  encryption:
    key: "Mdi6czWy+lKqz7k6OZ9CK37gOsbWW6YZDrYX1qjZyk4="

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
